### ISSUE TITLE
2013.1.beta.7 - modifying record produces fatal error.

### ISSUE THREAD

**Issue by KorvinM** [simpleinvoices/simpleinvoices#172]
Hello, testing the 2013.1.beta.7
Attempting to add an email address to an existing customer's record produced the following error (i've masked the domain i'm using).

Fatal error: Function name must be a string in /[domain]/public_html/simple-invoices/include/sql_queries.php on line 1511﻿

**Comment by Harribo19** [comment]
also :
return dbQquery($sql,

should be:
return dbQuery($sql,

**Comment by apmuthu** [comment]
The said error was introduced in the [commit on Oct 27, 2013 ](https://github.com/simpleinvoices/simpleinvoices/commit/edef0c2f44bea2adcde1046976d92dc9d5e72c32) and was rectified in the [commit on Nov 9, 2013](https://github.com/simpleinvoices/simpleinvoices/commit/c564841ee1807d8d3fcdf10e7faac37b133a0c7b).

Please review the current code in the master before reporting errors.in old code.

Those following my fork can follow the [commit on Oct 30, 2013](https://github.com/apmuthu/simpleinvoices/commit/1e1b853c81dba1cf2e7abcac596663b257985bad) that fixed it.

**Comment by Harribo19** [comment]
I dont understand this

**Comment by apmuthu** [comment]
Use the [stable master](https://github.com/simpleinvoices/simpleinvoices/archive/master.zip) with dependancies

**Comment by Harribo19** [comment]
But the stable master is a lot older version? (2011)
So I will be missing certain features right now?

**Comment by apmuthu** [comment]
The stable master had it's last commit on Mar 27, 2015.
![2015-07-23_220951](https://cloud.githubusercontent.com/assets/2995044/8856289/906ec4f6-3187-11e5-9b71-2ede35af335d.png)

**Comment by Harribo19** [comment]
Aha ok
Sorry but I dont know my way through this

Now I have installed the stable master and it looks great but the customer columns are not good. For example, column name shows the id of the customer instead of the name; column total shows the name of the customer. The rest of the master version seems fine.,

I can ask you now but it would be smarter to know where I can find answers when I have a problem.
Like I said, I am not familiar with this, I dont know my way here (github,google+).

**Comment by apmuthu** [comment]
First extract the latest stable release [SI v2013.1.beta.7 dated 2013-10-28](https://bitbucket.org/simpleinvoices/simpleinvoices/downloads/simpleinvoices.2013.1.beta.7.zip). The overwrite the files with those of the [latest github](https://github.com/simpleinvoices/simpleinvoices/archive/master.zip) master ( I use [mine](https://github.com/apmuthu/simpleinvoices/archive/master.zip) ) so that the original dependencies will remain intact. Now install SI and see if your problems go away.

**Comment by Harribo19** [comment]
Thanks, this works!
