### ISSUE TITLE
Duplicate / copy a quote as invoice

### ISSUE THREAD

**Issue by vvcares** [simpleinvoices/simpleinvoices#263]
Currently we able to change the Quote > as> invoice.
But is it possible to copy the quote as a new invoice.? (so the quote also still will be exist)

**Comment by apmuthu** [comment]
Copy the Quote as a new Quote and then change the new Quote to Invoice!

**Comment by vvcares** [comment]
Hi Muthu,
Sorry, i didnt see any COPY option on quotes itself.
https://s6.postimg.org/px7dvpde9/Capture.png

**Comment by apmuthu** [comment]
Kindly post a screenshot of an edit invoice page where you see the copy icon so that we can match the screens as I dod not see one there as well.

You can meanwhile try **Recurrence** feature as below:

![1_si_quote_list](https://cloud.githubusercontent.com/assets/2995044/21793518/24abf5da-d718-11e6-9e1d-51eae5ea7a4d.png)
![2_si_recurrence](https://cloud.githubusercontent.com/assets/2995044/21793519/28cdcd0a-d718-11e6-9672-d19f9d1a97f2.png)
![3_si_new_recurrence](https://cloud.githubusercontent.com/assets/2995044/21793523/2c72fee4-d718-11e6-98fe-ca40ca345405.png)

**Comment by vvcares** [comment]
Hi Muthu. Seems you get confused my request. :-).
I dont have such copy option. 
My request is : Is there any possibility to copy any quote/invoice to create new invoice ? :-)

**Comment by apmuthu** [comment]
Create an Invoice (or Quote).
Make it a "Recurrent" one even if just once. This will generate another Invoice with the same Items, Customer and Biller where you can edit at will.
The above is the equivalent of "Copy".
There is no separate "Copy" function button for the feature.

**Comment by vvcares** [comment]
Hi. Ok. Thank you for uour prompt supports. 😊
